name: golly_express_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
    
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
  fonts:
      - family: 'Dm Sans'
        fonts:
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
